#Pull the latest UBUNTU base image 

#Install python and python dependencies

#set working dir (this will be home directory of the docker file)

#Copy source code to the docker container

#Install dependencies

#expose port

#set entrypoint and command

